services:
  - type: web
    name: ecodry-app
    env: python
    region: oregon
    plan: free
    buildCommand: cd inte/inte && pip install -r ../../requirements.txt
    startCommand: cd inte/inte && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
